### PR TITLE
Rr 28/create new item

### PR DESCRIPTION
**Pull request by Ben-ayesu**
Create an API to allow for the creation of  a new inventory item attached to a given warehouse.

POST /api/inventories

### CODE REVIEW

**Comment by Green-Eggs-And-SAM** [comment]
please change the file name from 

warehouse-controllers.js

to 

warehouse-controller.js

thank you.
Going to test the code now.

**Comment by Green-Eggs-And-SAM** [comment]
uh oh! make sure you are merging with develop branch not main branch.

**Comment by Ben-ayesu** [comment]
> uh oh! make sure you are merging with develop branch not main branch.

Good catch 🙏🏿

**Comment by Green-Eggs-And-SAM** [comment]
Hey! the code works great. just change the filename to warehouse-controller.js (no 's')and the corresponding 'require' on line 3 of warehouses-route.js and we should be good to merge

**Review by nicmart-dev — COMMENTED** [review]
Great work with validation, happy path works but errors like invalid warehouse id return status 500, likely as your 400 status handling should be part of the catch block too, like the 500 one:

image

image

**Review by nicmart-dev — CHANGES_REQUESTED** [review]
Great work with validation, happy path works but errors like invalid warehouse id return status 500, likely as your 400 status handling should be part of the catch block too, like the 500 one:

image

image

**Comment by Ben-ayesu** [comment]
Thanks @nicmart-dev  and @Green-Eggs-And-SAM . Fixed the check on the warehouse id!

**Review by Green-Eggs-And-SAM — APPROVED** [review]
looks great thanks!

**Pull request merged**
